### ISSUE TITLE
Evaluation with weak attack, plus evaluation results do not match README

### ISSUE THREAD

**Issue by cassidylaidlaw** [ddkang/advex-uar#2]
Hello, thanks for the interesting work. I agree that testing against unforeseen perturbation types is important and I appreciate you taking steps to create a benchmark.

I was trying to recreate some of the CIFAR10 ATA numbers. I used your pretrained models and evaluation script, but I'm getting different accuracies than what you report in the README.

For example, the ATA for Linf with eps4 (8) on CIFAR10: you report 71% but running the following command I get an accuracy of ~62%:

    python advex_uar/examples/eval.py --dataset cifar-10 --attack pgd_linf --epsilon 8 --n_iters 100 --step_size 1 --ckpt_path adv-cifar10-models/pgd-linf-8.pth --dataset_path ~/datasets/ --resnet_size 56

In another case, the ATA for L2 with eps4 (320) on CIFAR10: you report 67% but running the following command I get an accuracy of ~59%:

    python advex_uar/examples/eval.py --dataset cifar-10 --attack pgd_l2 --epsilon 320 --n_iters 100 --step_size 20 --ckpt_path adv-cifar10-models/pgd-l2-320.pth --dataset_path ~/datasets/ --resnet_size 56

The most concerning thing is that your evaluation seems to be using a targeted attack with only one randomly selected target. I tried changing lines 99-100 in evaluator.py to the following to do an untargeted attack:

    data_adv = self.attack(self.model, data, target,
                           avoid_target=True, scale_eps=False)

Then running the Linf eps4 (8) evaluation as above gives an accuracy of ~29%, which is way below your reported 71%.

Am I doing something wrong here? It seems like you should evaluate ATA using the strongest possible attack, and the untargeted attack is clearly stronger.

**Comment by yi-sun** [comment]
Thanks for your interest in our work and for trying to use our code.

Regarding the ATA values, the reason for your results is that the ATA value is estimated using the best adversarially trained model against an attack.  For Linf eps=8, it is trained against Linf eps=16, and for L2 eps=320 it is L2 eps=640.  Evaluating against these models should give the ATA values in our table.  In addition, please note that for Linf and L2 our results are reported with 200-step attacks with step size eps / sqrt(steps) (note that this works slightly differently for Fog, Gabor, and Snow). 

Regarding the use of random targets, we are using an (incorrect) target class chosen uniformly at random for each input image as is customary for ImageNet (https://arxiv.org/abs/1802.00420).  I just verified that this is the case empirically.  Are you seeing something different?

Regarding the use of untargeted attacks for CIFAR-10, our current results are for targeted adversarial training and evaluation on CIFAR-10 to be consistent with our ImageNet-100 results.  As you mention, it may make sense to use untargeted attacks for CIFAR-10 instead (since there is no risk of simply perturbing the class to a closely related class).  We may consider updating the CIFAR-10 version of our code to account for this in the future.

**Comment by cassidylaidlaw** [comment]
Thanks for the clarification. I do agree that you are using an incorrect target class chosen randomly for the attack; that makes sense for ImageNet. I'm not sure it makes as much sense for CIFAR-10 but I appreciate you providing your rationale.
